# Jekyll configuration for PulumiCost Documentation
# Deployed to GitHub Pages from /docs directory

title: PulumiCost Documentation
description: Cost visibility for Pulumi infrastructure. Calculate projected and actual costs with a plugin-based architecture.
baseurl: "/pulumicost-core"
url: "https://rshade.github.io"

# Site metadata
author: "PulumiCost Community"
email: "support@pulumicost.com"
github_username: rshade
repository: rshade/pulumicost-core

# Theme configuration
theme: jekyll-theme-minimal
minimal:
  skin: light

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Syntax highlighting
highlighter: rouge
rouge_style: github

# Collection configuration (optional, for organizing content)
collections:
  guides:
    output: true
    permalink: /:path/
  architecture:
    output: true
    permalink: /:path/
  plugins:
    output: true
    permalink: /:path/

# Exclude files from build
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "node_modules"
  - ".git"
  - ".gitignore"
  - "package.json"
  - "package-lock.json"
  - ".markdownlintrc.json"
  - ".markdown-link-check.json"
  - ".vale.ini"
  - "*.md.bak"
  - "**/.DS_Store"
  - "**/Thumbs.db"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-sitemap

# Google Analytics (optional, uncomment to enable)
# google_analytics_id: UA-XXXXXXXXX-X

# Permalinks
permalink: /docs/:title/

# Keep files
keep_files:
  - CNAME
  - assets

# Build settings
safe: true
lsi: false
incremental: true
limit_posts: 0

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      toc: true
  - scope:
      path: "getting-started"
      type: "pages"
    values:
      layout: "default"
      category: "getting-started"
  - scope:
      path: "guides"
      type: "pages"
    values:
      layout: "default"
      category: "guides"
  - scope:
      path: "architecture"
      type: "pages"
    values:
      layout: "default"
      category: "architecture"
  - scope:
      path: "plugins"
      type: "pages"
    values:
      layout: "default"
      category: "plugins"
  - scope:
      path: "reference"
      type: "pages"
    values:
      layout: "default"
      category: "reference"
  - scope:
      path: "deployment"
      type: "pages"
    values:
      layout: "default"
      category: "deployment"
  - scope:
      path: "support"
      type: "pages"
    values:
      layout: "default"
      category: "support"

# Liquid options
liquid:
  error_mode: strict

# Show draft posts
show_drafts: false

# Full rebuild
full_rebuild: false

# Future posts
future: false

# Custom variables
version: "0.1.0"
status: "In Development"

# Navigation (optional, if using custom nav)
nav_items:
  - title: "Getting Started"
    url: "/pulumicost-core/getting-started/"
  - title: "Guides"
    url: "/pulumicost-core/guides/"
  - title: "Architecture"
    url: "/pulumicost-core/architecture/"
  - title: "Plugins"
    url: "/pulumicost-core/plugins/"
  - title: "Reference"
    url: "/pulumicost-core/reference/"
  - title: "Deployment"
    url: "/pulumicost-core/deployment/"
  - title: "Support"
    url: "/pulumicost-core/support/"

# Search configuration (for future search implementation)
search:
  enabled: true
  index_pages: true

# Compression (improve performance)
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Cache control
timezone: UTC
