source 'https://rubygems.org'

# Jekyll and theme
gem 'jekyll', '~> 4.3'
gem 'jekyll-theme-minimal', '~> 0.2'

# Jekyll plugins
gem 'jekyll-include-cache', '~> 0.2'
gem 'jekyll-sitemap', '~> 1.4'

# Markdown processing
gem 'kramdown', '~> 2.4'
gem 'rouge', '~> 4.1'

# Development dependencies
group :development do
  gem 'bundler', '~> 4.0'
  gem 'rake', '~> 13.0'
  gem 'webrick', '~> 1.8'
end
